### PR TITLE
[WIP] Add further attributes

### PR DESCRIPTION
**Pull request by JCWasmx86**
Not ready for merging, just for providing some sort of tracker.

The tests are still failing

### CODE REVIEW

**Comment by Col-E** [comment]
Oh, right when I did rebasing on develop that messed up the git history here... uh in case you do continue don't worry about it, I'll sort it out on my end when you're ready to merge.

**Comment by JCWasmx86** [comment]
I would say, you do it like you wish. I'm quite flexible with that

**Comment by JCWasmx86** [comment]
I would say, that this are enough new attributes for one PR in order to avoid having a too big review.

**Comment by Col-E** [comment]
Sorry for the delay, great work all around! Will push up the merged code in a bit.

**Comment by Col-E** [comment]
Merged! Sorry about my dumb rebase from earlier, it confuses github's merge detection but you can see your changes up on the `master` branch now 👍

**Pull request closed without merging**
